// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8q1MET4pYoz3DLTZ1_Pzhf4zqjci3RSc',
    appId: '1:165808314546:web:d65bd47edc8e1e35c011ab',
    messagingSenderId: '165808314546',
    projectId: 'reno-vision',
    authDomain: 'reno-vision.firebaseapp.com',
    storageBucket: 'reno-vision.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3IWkgY0PxPInWfZpl4CHAgyRN1DuSSpg',
    appId: '1:165808314546:android:9d63d4f7ac895d76c011ab',
    messagingSenderId: '165808314546',
    projectId: 'reno-vision',
    storageBucket: 'reno-vision.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM_eLYCv_LWcaba2-AAQ7ZmXmAPv9EAJ8',
    appId: '1:165808314546:ios:06b9d37ab21e0df1c011ab',
    messagingSenderId: '165808314546',
    projectId: 'reno-vision',
    storageBucket: 'reno-vision.appspot.com',
    iosBundleId: 'com.example.RenoVision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM_eLYCv_LWcaba2-AAQ7ZmXmAPv9EAJ8',
    appId: '1:165808314546:ios:27db063099fe95c1c011ab',
    messagingSenderId: '165808314546',
    projectId: 'reno-vision',
    storageBucket: 'reno-vision.appspot.com',
    iosBundleId: 'com.example.renovisionApp.RunnerTests',
  );
}
